# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='Description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='card',
            name='subject',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
